name: coodehub
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  get: ^4.6.5
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  google_fonts: ^5.1.0
  email_validator: ^2.1.17
  get_storage: ^2.1.1
  page_transition: ^2.0.9
  carousel_slider: ^4.2.1
  zoom_tap_animation: ^1.1.0
  iconly: ^1.0.1
  connectivity_plus: ^4.0.2
  smooth_page_indicator: ^1.1.0
  velocity_x: ^4.1.1
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.1.14
  dart_openai: ^4.0.0
  hive: ^2.2.3
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.9
  hive_flutter: ^1.1.0
  firebase_core: ^2.15.1
  youtube_player_flutter: ^8.1.2
  visibility_detector: ^0.4.0+2
  flutter_inappwebview: ^5.7.2+3
  awesome_notifications: ^0.7.7
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/codehub.png"

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

assets:
  - assets/images/
