// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNGtTscXsbUFLTCKgAPZNzTCDtWLcKDB0',
    appId: '1:394537922276:web:a4da07ca4f33324a5146f1',
    messagingSenderId: '394537922276',
    projectId: 'codehub-tech',
    authDomain: 'codehub-tech.firebaseapp.com',
    storageBucket: 'codehub-tech.appspot.com',
    measurementId: 'G-EKELN898ME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVt9TLAO8b7cegvn8tPK-KX8qNrfMnw2A',
    appId: '1:394537922276:android:2ade13d33813385c5146f1',
    messagingSenderId: '394537922276',
    projectId: 'codehub-tech',
    storageBucket: 'codehub-tech.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNcLNbO0z5mUHCVOghPenBcLtoZsTa5tk',
    appId: '1:394537922276:ios:dc9d190350f067125146f1',
    messagingSenderId: '394537922276',
    projectId: 'codehub-tech',
    storageBucket: 'codehub-tech.appspot.com',
    iosClientId: '394537922276-bmjqjsv3s0je8t8qhibl9p4ithbs4m2g.apps.googleusercontent.com',
    iosBundleId: 'com.example.coodehub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNcLNbO0z5mUHCVOghPenBcLtoZsTa5tk',
    appId: '1:394537922276:ios:6eb2e911c2c77f0e5146f1',
    messagingSenderId: '394537922276',
    projectId: 'codehub-tech',
    storageBucket: 'codehub-tech.appspot.com',
    iosClientId: '394537922276-9fvus6ls8mer9qvpciged2d6tfcaf2gu.apps.googleusercontent.com',
    iosBundleId: 'com.example.coodehub.RunnerTests',
  );
}
